/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/buyerhome`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/vendorhome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/buyer/BuyerProfie`; params?: Router.UnknownInputParams; } | { pathname: `/buyer/editProfileBuyer`; params?: Router.UnknownInputParams; } | { pathname: `/styles/LoginStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/SignupStyles`; params?: Router.UnknownInputParams; } | { pathname: `/vendor/editProfileVendor`; params?: Router.UnknownInputParams; } | { pathname: `/vendor/VendorProfile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/buyerhome`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/splash`; params?: Router.UnknownOutputParams; } | { pathname: `/vendorhome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/buyer/BuyerProfie`; params?: Router.UnknownOutputParams; } | { pathname: `/buyer/editProfileBuyer`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/LoginStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/SignupStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/vendor/editProfileVendor`; params?: Router.UnknownOutputParams; } | { pathname: `/vendor/VendorProfile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/buyerhome${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/splash${`?${string}` | `#${string}` | ''}` | `/vendorhome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/buyer/BuyerProfie${`?${string}` | `#${string}` | ''}` | `/buyer/editProfileBuyer${`?${string}` | `#${string}` | ''}` | `/styles/LoginStyles${`?${string}` | `#${string}` | ''}` | `/styles/SignupStyles${`?${string}` | `#${string}` | ''}` | `/vendor/editProfileVendor${`?${string}` | `#${string}` | ''}` | `/vendor/VendorProfile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/buyerhome`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/vendorhome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/buyer/BuyerProfie`; params?: Router.UnknownInputParams; } | { pathname: `/buyer/editProfileBuyer`; params?: Router.UnknownInputParams; } | { pathname: `/styles/LoginStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/SignupStyles`; params?: Router.UnknownInputParams; } | { pathname: `/vendor/editProfileVendor`; params?: Router.UnknownInputParams; } | { pathname: `/vendor/VendorProfile`; params?: Router.UnknownInputParams; };
    }
  }
}
